// The paper's worked examples, run through the verifier the paper describes. The output
// is a source in the review: a sentence that says what the verifier does quotes this
// line, not the author's word for it. Regenerated by regenerate.mjs (id: verifier).
import { verifyProveml } from 'proveml/verify';
import { renderProveml } from 'proveml/render';

const store = {
  'company:aapl.name': 'Apple Inc.',
  'company:aapl.revenue': 391035000000, 'company:aapl.revenue._unit': 'USD', 'company:aapl.revenue._display': 'currency:USD:1',
  'company:aapl.netIncome': 93736000000, 'company:aapl.netIncome._unit': 'USD', 'company:aapl.netIncome._display': 'currency:USD:1',
};
const line = (md, label) => {
  const r = verifyProveml(md, store);
  const d = r.details[r.details.length - 1];
  console.log(`${label}: claim ${md.replace(/^.*?(%\[[^\]]*\]\{[^}]*\}).*$/, '$1')} against ${d.path || ''} = ${store[d.path]}: ${d.status}${d.display ? `, shown as ${d.display}` : ''}`);
};
console.log(`store: company:aapl.revenue = 391035000000, display rule currency:USD:1`);
line('@[company:aapl]{Apple Inc.} reported revenue of %[revenue]{391035000000 USD}.', 'canonical value');
line('@[company:aapl]{Apple Inc.} reported revenue of %[revenue]{$391 billion}.', 'rounded value');
line('@[company:aapl]{Apple Inc.} reported net income of %[netIncome]{93736000000 USD}.', 'net income');
const { html } = renderProveml('@[company:aapl]{Apple Inc.} reported revenue of %[revenue]{391035000000 USD}.', store);
console.log(`render: the reader sees ${/>(\$[0-9.]+ billion)</.exec(html)?.[1] || 'no display form'}, the audit keeps 391035000000 USD`);
// Coverage: which numbers count as inside a claim. Facts do; a number in an entity's display name
// or in prose does not; years, list markers and code are left out of the denominator.
{
  const md = '@[company:aapl]{Apple Inc.} reported revenue of %[revenue]{391035000000 USD} across 2 segments in 2025.';
  const r = verifyProveml(md, store);
  console.log(`coverage: one fact claim with a digit and one prose number (2 segments; the year 2025 excluded): marked ${r.coverage.marked} (numbers inside a fact claim), unmarked ${r.coverage.unmarked} (numbers in prose), rate ${r.coverage.rate}`);
}
// Entities: the display name is checked against the store's name at that id.
{
  for (const [md, label] of [['@[company:aapl]{Apple Inc.} reported.', 'entity name'], ['@[company:aapl]{Apple} reported.', 'wrong entity name']]) {
    const r = verifyProveml(md, store); const d = r.details.find((x) => x.type === 'entity') || r.details[0];
    console.log(`${label}: ${md.match(/@\[[^\]]*\]\{[^}]*\}/)[0]} against company:aapl.name = ${store['company:aapl.name']}: ${d.status}`);
  }
}
// The other two fact outcomes: a field the store does not hold, and a fact with no entity in force.
{
  const r1 = verifyProveml('@[company:aapl]{Apple Inc.} reported %[headcount]{164000}.', store); const d1 = r1.details.find((x) => x.type === 'fact');
  console.log(`unverifiable: claim %[headcount]{164000} against company:aapl.headcount, which the store does not hold: ${d1.status}`);
  const r2 = verifyProveml('Revenue was %[revenue]{391035000000 USD}.', store); const d2 = r2.details.find((x) => x.type === 'fact');
  console.log(`no context: claim %[revenue]{391035000000 USD} with no entity in force: ${d2.status}`);
}
// Judgments: a condition is a registered name; a comparison written by the model, or a name the registry lacks, is unverifiable.
{
  for (const [md, label] of [['@[company:aapl]{Apple Inc.} had ?[p: revenue > 100]{strong revenue}.', 'bare comparison'], ['@[company:aapl]{Apple Inc.} had ?[p: IS_HUGE_REVENUE]{strong revenue}.', 'unregistered name']]) {
    const r = verifyProveml(md, store); const d = r.details.find((x) => x.type === 'inference');
    console.log(`${label}: ${md.match(/\?\[[^\]]*\]\{[^}]*\}/)[0]}: ${d.status} (${d.error})`);
  }
}
// The registry is an argument of the verifier, given by the deployment: the same judgment verifies only when the
// deployment has declared the name, and nothing in the text can declare one.
{
  const md = '@[company:aapl]{Apple Inc.} had ?[p: IS_HUGE_REVENUE]{huge revenue}.';
  const registry = { IS_HUGE_REVENUE: { field: 'revenue', op: '>=', value: 100000000000, label: 'huge revenue', source: 'this script' } };
  const withIt = verifyProveml(md, store, { thresholds: registry }).details.find((x) => x.type === 'inference');
  console.log(`registry from outside: the deployment passes {IS_HUGE_REVENUE: revenue >= 100000000000} to the verifier and the same judgment is ${withIt.status}; without it, unverifiable (line above)`);
}
