// The paper's worked examples, run through the verifier the paper describes. The output
// is a source in the review: a sentence that says what the verifier does quotes this
// line, not the author's word for it. Regenerated by regenerate.mjs (id: verifier).
import { verifyProveml } from 'proveml/verify';
import { renderProveml } from 'proveml/render';

const store = {
  'company:aapl.name': 'Apple Inc.',
  'company:aapl.revenue': 391035000000, 'company:aapl.revenue._unit': 'USD', 'company:aapl.revenue._display': 'currency:USD:1',
  'company:aapl.netIncome': 93736000000, 'company:aapl.netIncome._unit': 'USD', 'company:aapl.netIncome._display': 'currency:USD:1',
};
const line = (md, label) => {
  const r = verifyProveml(md, store);
  const d = r.details[r.details.length - 1];
  console.log(`${label}: claim ${md.replace(/^.*?(%\[[^\]]*\]\{[^}]*\}).*$/, '$1')} against ${d.path || ''} = ${store[d.path]}: ${d.status}${d.display ? `, shown as ${d.display}` : ''}`);
};
console.log(`store: company:aapl.revenue = 391035000000, display rule currency:USD:1`);
line('@[company:aapl]{Apple Inc.} reported revenue of %[revenue]{391035000000 USD}.', 'canonical value');
line('@[company:aapl]{Apple Inc.} reported revenue of %[revenue]{$391 billion}.', 'rounded value');
line('@[company:aapl]{Apple Inc.} reported net income of %[netIncome]{93736000000 USD}.', 'net income');
const { html } = renderProveml('@[company:aapl]{Apple Inc.} reported revenue of %[revenue]{391035000000 USD}.', store);
console.log(`render: the reader sees ${/>(\$[0-9.]+ billion)</.exec(html)?.[1] || 'no display form'}, the audit keeps 391035000000 USD`);
